// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjHVGvwT2f8DhVTQE2k7rZVtDg9tV0xOI',
    appId: '1:558737701925:web:1ea5ef8386fd3e557353cc',
    messagingSenderId: '558737701925',
    projectId: 'cuahanghoa-doan',
    authDomain: 'cuahanghoa-doan.firebaseapp.com',
    databaseURL: 'https://cuahanghoa-doan-default-rtdb.firebaseio.com',
    storageBucket: 'cuahanghoa-doan.firebasestorage.app',
    measurementId: 'G-QZGMS9NPX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADa2DAz3Gtg2UschYbJuAmIcmelCq8YL8',
    appId: '1:558737701925:android:d859be6dc0acd5e47353cc',
    messagingSenderId: '558737701925',
    projectId: 'cuahanghoa-doan',
    databaseURL: 'https://cuahanghoa-doan-default-rtdb.firebaseio.com',
    storageBucket: 'cuahanghoa-doan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjHVGvwT2f8DhVTQE2k7rZVtDg9tV0xOI',
    appId: '1:558737701925:web:51ec81da4a1494cd7353cc',
    messagingSenderId: '558737701925',
    projectId: 'cuahanghoa-doan',
    authDomain: 'cuahanghoa-doan.firebaseapp.com',
    databaseURL: 'https://cuahanghoa-doan-default-rtdb.firebaseio.com',
    storageBucket: 'cuahanghoa-doan.firebasestorage.app',
    measurementId: 'G-5NJDBYHKGX',
  );
}
